### ISSUE TITLE
Remaining issues with bad channels

### ISSUE THREAD

**Issue by yanbin-niu** [NDCLab/pepper-pipeline#163]
**Issue 1 - the reference channel:**

@DMRoberts mentioned:

> although the BIDS format has a field for a reference channel, MNE doesn’t have a field in their EEG data structure for it. There is an open issue on the MNE Github about adding such a field, but I don’t think it has been implemented yet. I assume after it is added then MNE-BIDS will be able to populated it from the value in the BIDS json sidecar: https://github.com/mne-tools/mne-python/issues/8962
> Another potential issue is that although the BIDS format requires an EEG Reference to be specified, I don’t think it is specific on the format. For example the ‘EEG Matching Pennies’ example dataset (https://github.com/bids-standard/bids-examples/blob/master/eeg_matchingpennies/task-matchingpennies_eeg.json ) states for the reference:
> `unipolar, placed on Fz`
> Instead of just indicating ‘Fz’, so some parsing of the string would need needed to interpret correctly.

Solution:
1. read in the “eeg.json” sidecar file independently from MNE-BIDS and try to parse the EEG reference;
2. require it in the user_params.json (could allow the user to specify in user_params.json that would overwrite the value in the “*eeg.json” sidecar file, etc.)

**Issue 2 - coordinates after `set_montage`:**
1. in the GSN-HydroCel-129.sfp, the coordinates:
![](https://user-images.githubusercontent.com/79607547/119266104-0988d280-bc1c-11eb-819e-0fa29dc35f0b.png)

2. However, in MNE, after `set_montage` the coordinates:
![](https://user-images.githubusercontent.com/79607547/119266202-6be1d300-bc1c-11eb-9e4a-06c8016314e8.png)

Need to figure out the source of the discrepancy which will potentially impact the calculation of distance.

**Comment by georgebuzzell** [comment]
@yanbin-niu Thank you for bringing this up. I think that the solution for now, is to have the user specify the reference in the input json file. However, please also open an issue to update feature-io in the future so that feature-io reads in the reference.

**Comment by georgebuzzell** [comment]
@yanbin-niu for the montage and sfp file, I think that perhaps the reference frame is changing, as well as the units possible. Can you try plotting each? Also, is there information on what refrence frame that mne is using and the units? Likewise for the sfp file?

**Comment by yanbin-niu** [comment]
@georgebuzzell Sure! I want to confirm with @DMRoberts first the validity of including this in feature-io. Maybe also include montage info in the “*eeg.json” sidecar file (related to https://github.com/NDCLab/baseEEG/issues/26 or other preprocessing feature that needs to `set_montage`), but I am also not sure whether this is possible or there is a better way (both for reference channel and montage info).

**Comment by F-said** [comment]
Resolved with PR #180
