### ISSUE TITLE
Update feature-io to loop over participants

### ISSUE THREAD

**Issue by georgebuzzell** [NDCLab/pepper-pipeline#167]
**Describe the feature effect or output**
Currently, feature-io does not loop over participants. want to modify to loop over participants.

**Which part of the pipeline does this satisfy if any**
not part of pipeline. modification to feature-io

**What is the minimum for this feature to be complete?**
PR merged.

**Comment by DMRoberts** [comment]
@georgebuzzell can you provide additional datasets, for this, since I believe we only have the one .mff as is? Is the CMI data all in a single folder along with the 'HBN_R2_1_Pheno.csv' demographic file?

**Comment by georgebuzzell** [comment]
I think we already have additional data sets here, unless i misunderstand? https://drive.google.com/drive/u/0/folders/1aQY97T9EfkPEkuiCav2ei9cs0DFegO4-

The pheno data is split across files. Basically cmi releases the data in catches, with all the pheno data for one batch in a given file. I think the other subs should have their data in that same pheno file though. Let me know if I need to grab something else here though!

Thanks @DMRoberts

**Comment by F-said** [comment]
Close with PR #279
