### ISSUE TITLE
Implement testing module for segmenting 

### ISSUE THREAD

**Issue by F-said** [NDCLab/pepper-pipeline#168]
**Describe the feature to be tested**
Segment feature 

**Which tests need to be made for the feature**
Create a testing module that individually runs segment and checks for the following

- intermediate raw object
- output dictionary 

Along with the contents of the output.

**Comment by F-said** [comment]
Issue is too broad at the current state, limiting to set up of initial testing module for one feature.

**Comment by F-said** [comment]
Within the output dictionary, what kind of information should be guaranteed to be returned after segmenting is completed? 

This would be integrated as an automatic test. 
@georgebuzzell

**Comment by Jonhas** [comment]
@F-said @georgebuzzell  A guarantee could be that the unit test returns a set of valid epochs and a nonempty dictionary? When we instantiate an epochs object, mne checks for several attributes for validity, so a valid epochs object would mean a successful function pass? We can also check for ch_epochs > 0. Besides that, I'm not entirely sure.
