### ISSUE TITLE
Implement testing module for filter

### ISSUE THREAD

**Issue by F-said** [NDCLab/pepper-pipeline#171]
**Describe the feature to be tested**
Filter feature 

**Which tests need to be made for the feature**
Create a testing module that individually runs filter and checks for the following

- intermediate raw object
- output dictionary

~~Within the output dictionary, what kind of information should be guaranteed to be returned after filtering is completed? @georgebuzzell @yanbin-niu~~

**Comment by yanbin-niu** [comment]
@F-said For now filter only takes in high pass and low-pass, I don't think it has much info to return. We should expand into taking in notch filter and filter types, but still not much to return. Maybe the time it takes to finish filtering? @georgebuzzell
