### ISSUE TITLE
Implement testing module for bad-channels

### ISSUE THREAD

**Issue by F-said** [NDCLab/pepper-pipeline#172]
**Describe the feature to be tested**
Bad-channels

**Which tests need to be made for the feature**
Create a testing module that individually runs bad-channels and checks for the following

- intermediate raw object
- output dictionary

Within the output dictionary, what kind of information should be guaranteed to be returned after bad-channels is completed? @georgebuzzell @yanbin-niu

**Comment by yanbin-niu** [comment]
@F-said For now, bad-channel returns: 

{"badchans based on variances": bads_var,
 "badchans based on correlations": bads_cor,
"badchans based on hurst exponent": bads_hurst}

which indicates bad channels that have been identified by each criterion. It could be null for each.

**Comment by Jonhas** [comment]
@F-said @yanbin-niu I guess a way to approach if bad channels works properly is by testing if the dictionary isn't null. Alongside the dataset we have, we can also generate random noise to see how the bad channels algorithm treats this.
