### ISSUE TITLE
Implement testing module for ICA

### ISSUE THREAD

**Issue by F-said** [NDCLab/pepper-pipeline#173]
**Describe the feature to be tested**
ICA

**Which tests need to be made for the feature**
Create a testing module that individually runs ICA and checks for the following

- intermediate raw object
- output dictionary

Within the output dictionary, what kind of information should be guaranteed to be returned after the ICA is completed? @georgebuzzell @yanbin-niu

**Comment by yanbin-niu** [comment]
@F-said Ica now returns:

ica_details = {"original epochs": epochs_original,           # the number of epochs after arbitrary 1s segmentation
                    "bad epochs": epochs_bads,                         # the number of epochs that have been rejected
                    "bad epochs rate": epochs_bads / epochs_original,      # bad epochs rate 
                    "eog indices": eog_indices,                            # the indices of EOG related components, sorted by score
                    "eog_scores": eog_scores}                            # the correlation scores

items other than "original epochs" could be null.
