### ISSUE TITLE
Implement testing module for interpolate 

### ISSUE THREAD

**Issue by F-said** [NDCLab/pepper-pipeline#175]
**Describe the feature to be tested**
Interpolate feature 

**Which tests need to be made for the feature**
Create a testing module that individually runs interpolate and checks for the following

- intermediate raw object
- output dictionary

~~Within the output dictionary, what kind of information should be guaranteed to be returned after interpolating is completed? @georgebuzzell @Jonhas~~

**Comment by Jonhas** [comment]
@F-said @georgebuzzell With regards to interpolation, I can see several scenarios that we could encounter when interpolating. 

1. No bad channels are present 
2. Few bad channels are present 
3. How does the function react if the epochs aren't loaded? 
4. What if there are only a couple of channels? 
5. Does interpolation actually modify in place the data? 

Therefore, I believe we can try to test against these scenarios and also generate random noise to check how the interpolation function reacts to it. Maybe there is something else that you guys wish to be tested on?
