### ISSUE TITLE
Audit of CONTRIBUTING.md

### ISSUE THREAD

**Issue by F-said** [NDCLab/pepper-pipeline#205]
**What needs documentation and what will each item entail?**
Audit to check:
* Does CONTRIBUTING.md provide all the information required for a contributor to get started?

**Comment by jessb0t** [comment]
@F-said:
I pushed my suggested changes to dev-contrib-jess branch. This version of the .md file includes notes marked:

__________________FROM JESS
This is a note from me!
__________________FROM JESS

I added some comments about things that are in our template contributing, but note that they may not be fully relevant here, in which case they should be ignored!

Feel free to let me know if you'd like me to take another look once you've had the chance to digest my comments and suggestions! 🤠
