### ISSUE TITLE
Resolve path structure

### ISSUE THREAD

**Issue by georgebuzzell** [NDCLab/pepper-pipeline#22]
Location of scripts vs bids formatted data
location of raw data

**Comment by georgebuzzell** [comment]
@DMRoberts I think the issue you brought up previously was about the directory structure of where the data is being

**Comment by georgebuzzell** [comment]
Proposal:

For a given dataset, you should have a folder on your desktop with the name of the dataset. Inside of that dataset, everything should be organized in line with bids. Raw data goes in "sourceData". Git repo is named "code" and goes in code folder.

![image](https://user-images.githubusercontent.com/71228105/115035419-91035900-9e9a-11eb-8452-d2ee2961fc10.png)

**Comment by DMRoberts** [comment]
@georgebuzzell 

We'll have to think about this more, I think the setup might be complicated If we want:

- The development paths to match the BIDS paths as shown above (with the code inside the dataset)
- The BIDS dataset in a Docker volume during development

I'm not 100% sure at the moment, but I think we probably don't want the git repo for the code to be in the docker volume. I believe that theoretically the Docker volume could be shared between users, like the Docker image, or between Docker images if multiple projects use the same data. On the other hand I believe the local git repo would be unique to each user, if they have local changes they are working on before being pushed to the remote repository on Github. Having the code in the Docker Volume would also mean that commits would either need to be made from the Docker container, or copied back and forth from the container to the host OS.

The best option might be to see if we could mount the data inside a Volume, but then the code as a bind-mount between the host and container, but nested in the path of the data as shown in the BIDS example.

**Comment by DMRoberts** [comment]
@georgebuzzell I also see in the BIDS specifications that there is more than one way to include the sourcedata. One way is as you showed above, where sourcedata is at the same level as the 'raw' data files like 'sub-05'. The other way is listed here, where 'sourcedata' has a sibling folder 'rawdata' that would contain 'sub-05'. If for example a dataset contains hundreds or thousands of participants, it might be better to nest the raw data files within a 'rawdata' folder, or else folders like 'sourcedata' will be mixed in with a ton of sibling folders containing other types of data.

https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#source-vs-raw-vs-derived-data

**Comment by georgebuzzell** [comment]
@DMRoberts Thank you for thinking carefully about this. I agree that we should modify the path structure slightly as follows:

-inside the dataset folder, have sibling folders for "sourceData" and "rawData"
-sourceData is where the non-bids data goes
-rawData is where the bids formatted data goes
-everything else stays the same

**Comment by georgebuzzell** [comment]
@DMRoberts In terms of the solution for where the code should go, I don't want my wanting to have the code folder as a git repo inside the data folder as something to hold us up. So, if that is problematic, I am more than happy to go with an alternative, at least for now, that you think is something we can implement NOW and also that makes sense for organization. Do you have a suggestion?

The other option is to do the combination of volume and bind mounts, as you suggested. Or, we could ssh into the container as someone suggested.

@DMRoberts what do you suggest we move forward with?

@Jonhas @stevenwtolbert any comments here?

**Comment by F-said** [comment]
out of scope, closing
