### ISSUE TITLE
writing to dir does not work on HPC

### ISSUE THREAD

**Issue by F-said** [NDCLab/pepper-pipeline#255]
**Describe the bug**
`os.mkdir` does not grant proper permissions

**Expected behavior**
`os.mkdir` works same as local

**Screenshots**
>  File "/home/data/NDClab/scripts/base-eeg/scripts/data/write.py", line 70, in write_eeg_data
    os.mkdir(temp)  # creates the directory path
OSError: [Errno 30] Read-only file system: '/rawderivatives/'

**Comment by georgebuzzell** [comment]
@F-said curious if any progress here?

**Comment by F-said** [comment]
@georgebuzzell yep, resolved. Closing once I make merge to main pipeline with other batch of changes.

**Comment by F-said** [comment]
resolved
